import { toSlug } from "./utils";

/* Total 115 Games */
const products = [
  /* A Plague Tale Innocent */
  {
    name: "A Plague Tale Innocent (Steam)",
    slug: toSlug("A Plague Tale Innocent (Steam)"),
    image: "/images/games/A Plague Tale Innocent.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Standard",
    description:
      "A Plague Tale: Innocence is an action-adventure stealth game developed by Asobo Studio and published by Focus Home Interactive.",
    price: 1999,
    countInStock: 435,
    numSales: 69,
    releaseDate: "19-05-2019",
    developer: "Asobo Studio",
    review: 85,
    publisher: "Focus Home Interactive",
    delivery: "Digital Key",
  },
  {
    name: "A Plague Tale Innocent (PS)",
    slug: toSlug("A Plague Tale Innocent (PS)"),
    image: "/images/games/A Plague Tale Innocent.png",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Standard",
    description:
      "A Plague Tale: Innocence is an action-adventure stealth game developed by Asobo Studio and published by Focus Home Interactive.",
    price: 2299,
    countInStock: 355,
    numSales: 39,
    releaseDate: "19-05-2019",
    developer: "Asobo Studio",
    review: 88,
    publisher: "Focus Home Interactive",
    delivery: "Physical DVD",
  },

  /* A Plague Tale Requiem */

  {
    name: "A Plague Tale Requiem (Epic Game)",
    slug: toSlug("A Plague Tale Requiem (Epic Game)"),
    image: "/images/games/A Plague Tale Requiem.png",
    platform: "Epic Game",
    platformImageIcon: "/images/icons/epic-icon.png",
    edition: "Standard",
    description:
      "A Plague Tale: Requiem is an action-adventure stealth game developed by Asobo Studio and published by Focus Home Interactive.",
    price: 999,
    countInStock: 405,
    numSales: 12,
    releaseDate: "18-10-2022",
    developer: "Asobo Studio",
    review: 90,
    publisher: "Focus Home Interactive",
    delivery: "Ditigal Key",
  },

  /* AC Odyssey */
  {
    name: "Assassin's Creed Odyssey (Steam)",
    slug: toSlug("Assassin's Creed Odyssey (Steam)"),
    image: "/images/games/Assassin's Creed Odyssey.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Standard",
    description:
      "Assassin's Creed Odyssey is an action role-playing video game developed by Ubisoft Quebec and published by Ubisoft.",
    price: 1299,
    countInStock: 970,
    numSales: 678,
    releaseDate: "05-10-2018",
    developer: "Ubisoft Quebec",
    review: 95,
    publisher: "Ubisoft",
    delivery: "Ditigal Key",
  },
  {
    name: "Assassin's Creed Odyssey (Ubisoft)",
    slug: toSlug("Assassin's Creed Odyssey (Ubisoft)"),
    image: "/images/games/Assassin's Creed Odyssey.png",
    platform: "Ubisoft",
    platformImageIcon: "/images/icons/ubisoft-icon.png",
    edition: "Deluxe",
    description:
      "Assassin's Creed Odyssey is an action role-playing video game developed by Ubisoft Quebec and published by Ubisoft.",
    price: 1599,
    countInStock: 370,
    numSales: 128,
    releaseDate: "05-10-2018",
    developer: "Ubisoft Quebec",
    review: 93,
    publisher: "Ubisoft",
    delivery: "Account",
  },
  {
    name: "Assassin's Creed Odyssey (PS)",
    slug: toSlug("Assassin's Creed Odyssey (PS)"),
    image: "/images/games/Assassin's Creed Odyssey.png",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Ultimate",
    description:
      "Assassin's Creed Odyssey is an action role-playing video game developed by Ubisoft Quebec and published by Ubisoft.",
    price: 2099,
    countInStock: 340,
    numSales: 124,
    releaseDate: "05-10-2018",
    developer: "Ubisoft Quebec",
    review: 97,
    publisher: "Ubisoft",
    delivery: "Account",
  },

  /* AC Valhalla */
  {
    name: "Assassin's Creed Valhalla (Steam)",
    slug: toSlug("Assassin's Creed Valhalla (Steam)"),
    image: "/images/games/Assassin's Creed Valhalla.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Deluxe",
    description:
      "Assassin's Creed Valhalla is an action role-playing video game developed by Ubisoft Montreal and published by Ubisoft. It lets you become Eivor, a Viking raider in England’s Dark Ages.",
    price: 1299,
    countInStock: 250,
    numSales: 113,
    releaseDate: "10-11-2020",
    developer: "Ubisoft Montreal",
    review: 82,
    publisher: "Ubisoft",
    delivery: "Digital Key",
  },
  {
    name: "Assassin's Creed Valhalla (PS)",
    slug: toSlug("Assassin's Creed Valhalla (PS)"),
    image: "/images/games/Assassin's Creed Valhalla.png",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Deluxe",
    description:
      "Assassin's Creed Valhalla is an action role-playing video game developed by Ubisoft Montreal and published by Ubisoft. It lets you become Eivor, a Viking raider in England’s Dark Ages.",
    price: 1399,
    countInStock: 180,
    numSales: 94,
    releaseDate: "10-11-2020",
    developer: "Ubisoft Montreal",
    review: 84,
    publisher: "Ubisoft",
    delivery: "Physical DVD",
  },

  /* Ark Survival */
  {
    name: "Ark Survival (Steam)",
    slug: toSlug("Ark Survival (Steam)"),
    image: "/images/games/Ark Survival.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Survival Evolved",
    description:
      "ARK: Survival Evolved is an action-adventure survival game developed by Studio Wildcard. Players survive on an island filled with dinosaurs and other prehistoric animals.",
    price: 499,
    countInStock: 310,
    numSales: 158,
    releaseDate: "29-08-2017",
    developer: "Studio Wildcard",
    review: 76,
    publisher: "Studio Wildcard",
    delivery: "Digital Key",
  },
  {
    name: "Ark Survival (Xbox)",
    slug: toSlug("Ark Survival (Xbox)"),
    image: "/images/games/Ark Survival.png",
    platform: "Xbox",
    platformImageIcon: "/images/icons/xbox-icon.png",
    edition: "Survival Evolved",
    description:
      "ARK: Survival Evolved is an action-adventure survival game developed by Studio Wildcard. Players survive on an island filled with dinosaurs and other prehistoric animals.",
    price: 599,
    countInStock: 190,
    numSales: 102,
    releaseDate: "29-08-2017",
    developer: "Studio Wildcard",
    review: 74,
    publisher: "Studio Wildcard",
    delivery: "Digital Code",
  },
  /* Battlefield V */
  {
    name: "Battlefield V (EA)",
    slug: toSlug("Battlefield V (EA)"),
    image: "/images/games/Battlefield V.png",
    platform: "EA",
    platformImageIcon: "/images/icons/ea-icon.png",
    edition: "Standard",
    description:
      "Battlefield V is a first-person shooter developed by DICE and published by Electronic Arts. The game is based on World War II and focuses on large-scale multiplayer battles.",
    price: 899,
    countInStock: 400,
    numSales: 210,
    releaseDate: "20-11-2018",
    developer: "DICE",
    review: 78,
    publisher: "Electronic Arts",
    delivery: "Digital Key",
  },
  {
    name: "Battlefield V (Steam)",
    slug: toSlug("Battlefield V (Steam)"),
    image: "/images/games/Battlefield V.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Standard",
    description:
      "Battlefield V is a first-person shooter developed by DICE and published by Electronic Arts. The game is based on World War II and focuses on large-scale multiplayer battles.",
    price: 899,
    countInStock: 300,
    numSales: 165,
    releaseDate: "20-11-2018",
    developer: "DICE",
    review: 76,
    publisher: "Electronic Arts",
    delivery: "Digital Key",
  },
  /* Black Myth Wukong */
  {
    name: "Black Myth Wukong (Steam)",
    slug: toSlug("Black Myth Wukong (Steam)"),
    image: "/images/games/Black Myth Wukong.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Standard",
    description:
      "Black Myth: Wukong is an action RPG developed by Game Science, inspired by the Chinese novel Journey to the West. It features mythological creatures and fast-paced Souls-like combat.",
    price: 1690,
    countInStock: 350,
    numSales: 88,
    releaseDate: "20-08-2024",
    developer: "Game Science",
    review: 90,
    publisher: "Game Science",
    delivery: "Digital Key",
  },
  {
    name: "Black Myth Wukong (PS)",
    slug: toSlug("Black Myth Wukong (PS)"),
    image: "/images/games/Black Myth Wukong.png",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Standard",
    description:
      "Black Myth: Wukong is an action RPG developed by Game Science, inspired by the Chinese novel Journey to the West. It features mythological creatures and fast-paced Souls-like combat.",
    price: 1790,
    countInStock: 270,
    numSales: 52,
    releaseDate: "20-08-2024",
    developer: "Game Science",
    review: 89,
    publisher: "Game Science",
    delivery: "Physical DVD",
  },

  /* Call Of Duty Black Ops 6 */
  {
    name: "Call Of Duty Black Ops 6 (Microsoft)",
    slug: toSlug("Call Of Duty Black Ops 6 (Microsoft)"),
    image: "/images/games/Call Of Duty Black Ops 6.png",
    platform: "Microsoft",
    platformImageIcon: "/images/icons/microsoft-icon.png",
    edition: "Standard",
    description:
      "Call of Duty: Black Ops 6 is a first-person shooter developed by Treyarch and Raven Software, continuing the popular Black Ops series with intense multiplayer and campaign experiences.",
    price: 2390,
    countInStock: 290,
    numSales: 140,
    releaseDate: "25-10-2025",
    developer: "Treyarch, Raven Software",
    review: 87,
    publisher: "Activision",
    delivery: "Digital Key",
  },
  {
    name: "Call Of Duty Black Ops 6 (PS)",
    slug: toSlug("Call Of Duty Black Ops 6 (PS)"),
    image: "/images/games/Call Of Duty Black Ops 6.png",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Standard",
    description:
      "Call of Duty: Black Ops 6 is a first-person shooter developed by Treyarch and Raven Software, continuing the popular Black Ops series with intense multiplayer and campaign experiences.",
    price: 2490,
    countInStock: 220,
    numSales: 125,
    releaseDate: "25-10-2025",
    developer: "Treyarch, Raven Software",
    review: 89,
    publisher: "Activision",
    delivery: "Physical DVD",
  },

  /* Call Of Duty Modern Warfare III */
  {
    name: "Call Of Duty Modern Warfare III (Steam)",
    slug: toSlug("Call Of Duty Modern Warfare III (Steam)"),
    image: "/images/games/Call Of Duty Modern Warfare III.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Standard",
    description:
      "Call of Duty: Modern Warfare III is a first-person shooter developed by Sledgehammer Games and Infinity Ward. It continues the rebooted Modern Warfare storyline with modern action-packed gameplay.",
    price: 2290,
    countInStock: 310,
    numSales: 178,
    releaseDate: "10-11-2023",
    developer: "Sledgehammer Games, Infinity Ward",
    review: 81,
    publisher: "Activision",
    delivery: "Digital Key",
  },
  {
    name: "Call Of Duty Modern Warfare III (Xbox)",
    slug: toSlug("Call Of Duty Modern Warfare III (Xbox)"),
    image: "/images/games/Call Of Duty Modern Warfare III.png",
    platform: "Xbox",
    platformImageIcon: "/images/icons/xbox-icon.png",
    edition: "Standard",
    description:
      "Call of Duty: Modern Warfare III is a first-person shooter developed by Sledgehammer Games and Infinity Ward. It continues the rebooted Modern Warfare storyline with modern action-packed gameplay.",
    price: 2290,
    countInStock: 280,
    numSales: 132,
    releaseDate: "10-11-2023",
    developer: "Sledgehammer Games, Infinity Ward",
    review: 83,
    publisher: "Activision",
    delivery: "Digital Code",
  },

  /* Callisto Protocol */
  {
    name: "Callisto Protocol (Epic Game)",
    slug: toSlug("Callisto Protocol (Epic Game)"),
    image: "/images/games/Callisto Protocol.png",
    platform: "Epic Game",
    platformImageIcon: "/images/icons/epic-icon.png",
    edition: "Day One",
    description:
      "The Callisto Protocol is a survival horror game developed by Striking Distance Studios and published by Krafton. It delivers a story-driven, third-person experience set on Jupiter’s dead moon.",
    price: 1590,
    countInStock: 220,
    numSales: 92,
    releaseDate: "02-12-2022",
    developer: "Striking Distance Studios",
    review: 75,
    publisher: "Krafton",
    delivery: "Account",
  },
  {
    name: "Callisto Protocol (PS)",
    slug: toSlug("Callisto Protocol (PS)"),
    image: "/images/games/Callisto Protocol.png",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Day One",
    description:
      "The Callisto Protocol is a survival horror game developed by Striking Distance Studios and published by Krafton. It delivers a story-driven, third-person experience set on Jupiter’s dead moon.",
    price: 1690,
    countInStock: 190,
    numSales: 83,
    releaseDate: "02-12-2022",
    developer: "Striking Distance Studios",
    review: 78,
    publisher: "Krafton",
    delivery: "Physical DVD",
  },

  /* Control */

  {
    name: "Control (Epic Game)",
    slug: toSlug("Control (Epic Game)"),
    image: "/images/games/Control.png",
    platform: "Epic Game",
    platformImageIcon: "/images/icons/epic-icon.png",
    edition: "Ultimate",
    description:
      "Control is a third-person action-adventure game developed by Remedy Entertainment. Explore a mysterious government facility and harness supernatural abilities to uncover hidden truths.",
    price: 890,
    countInStock: 210,
    numSales: 98,
    releaseDate: "27-08-2019",
    developer: "Remedy Entertainment",
    review: 84,
    publisher: "505 Games",
    delivery: "Digital Key",
  },
  {
    name: "Control (PS)",
    slug: toSlug("Control (PS)"),
    image: "/images/games/Control.png",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Ultimate",
    description:
      "Control is a third-person action-adventure game developed by Remedy Entertainment. Explore a mysterious government facility and harness supernatural abilities to uncover hidden truths.",
    price: 990,
    countInStock: 170,
    numSales: 81,
    releaseDate: "27-08-2019",
    developer: "Remedy Entertainment",
    review: 87,
    publisher: "505 Games",
    delivery: "Physical DVD",
  },

  /* Cyberpunk 2077 */
  {
    name: "Cyberpunk 2077 (Steam)",
    slug: toSlug("Cyberpunk 2077 (Steam)"),
    image: "/images/games/Cyberpunk 2077.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Phantom Liberty Bundle",
    description:
      "Cyberpunk 2077 is an open-world RPG developed by CD Projekt Red, set in a dystopian future where players control V, a mercenary navigating the streets of Night City.",
    price: 1490,
    countInStock: 360,
    numSales: 208,
    releaseDate: "10-12-2020",
    developer: "CD Projekt Red",
    review: 86,
    publisher: "CD Projekt",
    delivery: "Digital Key",
  },

  {
    name: "Cyberpunk 2077 (PS)",
    slug: toSlug("Cyberpunk 2077 (PS)"),
    image: "/images/games/Cyberpunk 2077.png",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Phantom Liberty Bundle",
    description:
      "Cyberpunk 2077 is an open-world RPG developed by CD Projekt Red, set in a dystopian future where players control V, a mercenary navigating the streets of Night City.",
    price: 1590,
    countInStock: 220,
    numSales: 139,
    releaseDate: "10-12-2020",
    developer: "CD Projekt Red",
    review: 85,
    publisher: "CD Projekt",
    delivery: "Physical DVD",
  },
  {
    name: "Cyberpunk 2077 (Xbox)",
    slug: toSlug("Cyberpunk 2077 (Xbox)"),
    image: "/images/games/Cyberpunk 2077.png",
    platform: "Xbox",
    platformImageIcon: "/images/icons/xbox-icon.png",
    edition: "Phantom Liberty Bundle",
    description:
      "Cyberpunk 2077 is an open-world RPG developed by CD Projekt Red, set in a dystopian future where players control V, a mercenary navigating the streets of Night City.",
    price: 1590,
    countInStock: 180,
    numSales: 112,
    releaseDate: "10-12-2020",
    developer: "CD Projekt Red",
    review: 82,
    publisher: "CD Projekt",
    delivery: "Digital Code",
  },
  /* Death Stranding */
  {
    name: "Death Stranding (Steam)",
    slug: toSlug("Death Stranding (Steam)"),
    image: "/images/games/Death Stranding.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Director's Cut",
    description:
      "An open-world action game set in a fractured America. Developed by Kojima Productions and directed by Hideo Kojima.",
    price: 1350,
    countInStock: 312,
    numSales: 1340,
    releaseDate: "08-11-2019",
    developer: "Kojima Productions",
    review: 85,
    publisher: "505 Games",
    delivery: "Digital Key",
  },
  {
    name: "Death Stranding (PS)",
    slug: toSlug("Death Stranding (PS)"),
    image: "/images/games/Death Stranding.png",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Director's Cut",
    description:
      "An open-world action game set in a fractured America. Developed by Kojima Productions and directed by Hideo Kojima.",
    price: 1490,
    countInStock: 225,
    numSales: 980,
    releaseDate: "08-11-2019",
    developer: "Kojima Productions",
    review: 88,
    publisher: "Sony Interactive Entertainment",
    delivery: "Physical DVD",
  },
  {
    name: "Death Stranding (Epic Game)",
    slug: toSlug("Death Stranding (Epic Game)"),
    image: "/images/games/Death Stranding.png",
    platform: "Epic Game",
    platformImageIcon: "/images/icons/epic-icon.png",
    edition: "Director's Cut",
    description:
      "An open-world action game set in a fractured America. Developed by Kojima Productions and directed by Hideo Kojima.",
    price: 1350,
    countInStock: 195,
    numSales: 840,
    releaseDate: "08-11-2019",
    developer: "Kojima Productions",
    review: 83,
    publisher: "505 Games",
    delivery: "Digital Key",
  },

  /* Devil May Cry 5 */
  {
    name: "Devil May Cry 5 (Steam)",
    slug: toSlug("Devil May Cry 5 (Steam)"),
    image: "/images/games/Devil May Cry 5.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Special",
    description:
      "Join Dante and Nero in a high-octane demon-slaying action game from Capcom with stylish combat and epic bosses.",
    price: 990,
    countInStock: 387,
    numSales: 2510,
    releaseDate: "08-03-2019",
    developer: "Capcom",
    review: 89,
    publisher: "Capcom",
    delivery: "Digital Key",
  },
  {
    name: "Devil May Cry 5 (PS)",
    slug: toSlug("Devil May Cry 5 (PS)"),
    image: "/images/games/Devil May Cry 5.png",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Special",
    description:
      "Join Dante and Nero in a high-octane demon-slaying action game from Capcom with stylish combat and epic bosses.",
    price: 1190,
    countInStock: 179,
    numSales: 1120,
    releaseDate: "08-03-2019",
    developer: "Capcom",
    review: 90,
    publisher: "Capcom",
    delivery: "Physical DVD",
  },
  {
    name: "Devil May Cry 5 (Xbox)",
    slug: toSlug("Devil May Cry 5 (Xbox)"),
    image: "/images/games/Devil May Cry 5.png",
    platform: "Xbox",
    platformImageIcon: "/images/icons/xbox-icon.png",
    edition: "Special",
    description:
      "Join Dante and Nero in a high-octane demon-slaying action game from Capcom with stylish combat and epic bosses.",
    price: 1090,
    countInStock: 203,
    numSales: 980,
    releaseDate: "08-03-2019",
    developer: "Capcom",
    review: 87,
    publisher: "Capcom",
    delivery: "Digital Key",
  },

  /* Doom Eternal */
  {
    name: "Doom Eternal (Steam)",
    slug: toSlug("Doom Eternal (Steam)"),
    image: "/images/games/Doom Eternal.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Deluxe",
    description:
      "A high-speed, demon-slaying FPS from id Software. Continue the fight as the Doom Slayer in a battle against Hell's armies.",
    price: 1150,
    countInStock: 292,
    numSales: 1740,
    releaseDate: "20-03-2020",
    developer: "id Software",
    review: 91,
    publisher: "Bethesda Softworks",
    delivery: "Digital Key",
  },
  {
    name: "Doom Eternal (Microsoft)",
    slug: toSlug("Doom Eternal (Microsoft)"),
    image: "/images/games/Doom Eternal.png",
    platform: "Microsoft",
    platformImageIcon: "/images/icons/microsoft-icon.png",
    edition: "Deluxe",
    description:
      "A high-speed, demon-slaying FPS from id Software. Continue the fight as the Doom Slayer in a battle against Hell's armies.",
    price: 1150,
    countInStock: 120,
    numSales: 790,
    releaseDate: "20-03-2020",
    developer: "id Software",
    review: 88,
    publisher: "Bethesda Softworks",
    delivery: "Digital Key",
  },
  {
    name: "Doom Eternal (PS)",
    slug: toSlug("Doom Eternal (PS)"),
    image: "/images/games/Doom Eternal.png",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Deluxe",
    description:
      "A high-speed, demon-slaying FPS from id Software. Continue the fight as the Doom Slayer in a battle against Hell's armies.",
    price: 1290,
    countInStock: 161,
    numSales: 910,
    releaseDate: "20-03-2020",
    developer: "id Software",
    review: 90,
    publisher: "Bethesda Softworks",
    delivery: "Physical DVD",
  },
  /* Dragon Age Inquisition */

  {
    name: "Dragon Age Inquisition (EA)",
    slug: toSlug("Dragon Age Inquisition (EA)"),
    image: "/images/games/Dragon Age Inquisition.png",
    platform: "EA",
    platformImageIcon: "/images/icons/ea-icon.png",
    edition: "Game of the Year",
    description:
      "A fantasy RPG where you lead the Inquisition to restore order across Thedas. Shape your story with impactful choices.",
    price: 790,
    countInStock: 108,
    numSales: 710,
    releaseDate: "18-11-2014",
    developer: "BioWare",
    review: 81,
    publisher: "Electronic Arts",
    delivery: "Digital Key",
  },
  {
    name: "Dragon Age Inquisition (PS)",
    slug: toSlug("Dragon Age Inquisition (PS)"),
    image: "/images/games/Dragon Age Inquisition.png",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Game of the Year",
    description:
      "A fantasy RPG where you lead the Inquisition to restore order across Thedas. Shape your story with impactful choices.",
    price: 890,
    countInStock: 144,
    numSales: 880,
    releaseDate: "18-11-2014",
    developer: "BioWare",
    review: 86,
    publisher: "Electronic Arts",
    delivery: "Physical DVD",
  },

  /* Dragon Ball Z Kakarot */
  {
    name: "Dragon Ball Z Kakarot (Steam)",
    slug: toSlug("Dragon Ball Z Kakarot (Steam)"),
    image: "/images/games/Dragon Ball Z Kakarot.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Legendary",
    description:
      "Relive the story of Goku and other Z Fighters in this action-RPG that blends epic battles with life beyond fighting.",
    price: 1350,
    countInStock: 264,
    numSales: 1920,
    releaseDate: "17-01-2020",
    developer: "CyberConnect2",
    review: 82,
    publisher: "Bandai Namco Entertainment",
    delivery: "Digital Key",
  },
  {
    name: "Dragon Ball Z Kakarot (PS)",
    slug: toSlug("Dragon Ball Z Kakarot (PS)"),
    image: "/images/games/Dragon Ball Z Kakarot.png",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Legendary",
    description:
      "Relive the story of Goku and other Z Fighters in this action-RPG that blends epic battles with life beyond fighting.",
    price: 1490,
    countInStock: 118,
    numSales: 1120,
    releaseDate: "17-01-2020",
    developer: "CyberConnect2",
    review: 80,
    publisher: "Bandai Namco Entertainment",
    delivery: "Physical DVD",
  },
  {
    name: "Dragon Ball Z Kakarot (Nintendo)",
    slug: toSlug("Dragon Ball Z Kakarot (Nintendo)"),
    image: "/images/games/Dragon Ball Z Kakarot.png",
    platform: "Nintendo",
    platformImageIcon: "/images/icons/nintendo-icon.png",
    edition: "Legendary",
    description:
      "Relive the story of Goku and other Z Fighters in this action-RPG that blends epic battles with life beyond fighting.",
    price: 1350,
    countInStock: 97,
    numSales: 720,
    releaseDate: "17-01-2020",
    developer: "CyberConnect2",
    review: 78,
    publisher: "Bandai Namco Entertainment",
    delivery: "Physical Cartridge",
  },
  /* Elden Ring */
  {
    name: "Elden Ring (Steam)",
    slug: toSlug("Elden Ring (Steam)"),
    image: "/images/games/Elden Ring.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Standard",
    description:
      "Elden Ring is a vast action-RPG developed by FromSoftware, offering deep lore, open-world exploration, and brutal Souls-style combat.",
    price: 1790,
    countInStock: 311,
    numSales: 4521,
    releaseDate: "25-02-2022",
    developer: "FromSoftware",
    review: 95,
    publisher: "Bandai Namco Entertainment",
    delivery: "Digital Key",
  },
  {
    name: "Elden Ring (PS)",
    slug: toSlug("Elden Ring (PS)"),
    image: "/images/games/Elden Ring.png",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Standard",
    description:
      "Elden Ring is a vast action-RPG developed by FromSoftware, offering deep lore, open-world exploration, and brutal Souls-style combat.",
    price: 1990,
    countInStock: 187,
    numSales: 2390,
    releaseDate: "25-02-2022",
    developer: "FromSoftware",
    review: 94,
    publisher: "Bandai Namco Entertainment",
    delivery: "Physical DVD",
  },

  /* Evil West */
  {
    name: "Evil West (Steam)",
    slug: toSlug("Evil West (Steam)"),
    image: "/images/games/Evil West.jpg",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Standard",
    description:
      "Evil West is a third-person action game where you fight demonic forces in the Wild West with high-powered weapons and stylish combat.",
    price: 1190,
    countInStock: 89,
    numSales: 760,
    releaseDate: "22-11-2022",
    developer: "Flying Wild Hog",
    review: 77,
    publisher: "Focus Entertainment",
    delivery: "Digital Key",
  },

  /* Far Cry 5 */
  {
    name: "Far Cry 5 (Ubisoft)",
    slug: toSlug("Far Cry 5 (Ubisoft)"),
    image: "/images/games/Far Cry 5.png",
    platform: "Ubisoft",
    platformImageIcon: "/images/icons/ubisoft-icon.png",
    edition: "Gold",
    description:
      "Far Cry 5 is an open-world first-person shooter set in Montana, where you face off against a dangerous cult in a fight for freedom.",
    price: 890,
    countInStock: 193,
    numSales: 3099,
    releaseDate: "27-03-2018",
    developer: "Ubisoft Montreal",
    review: 84,
    publisher: "Ubisoft",
    delivery: "Digital Key",
  },
  {
    name: "Far Cry 5 (Steam)",
    slug: toSlug("Far Cry 5 (Steam)"),
    image: "/images/games/Far Cry 5.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Gold",
    description:
      "Far Cry 5 is an open-world first-person shooter set in Montana, where you face off against a dangerous cult in a fight for freedom.",
    price: 890,
    countInStock: 167,
    numSales: 2890,
    releaseDate: "27-03-2018",
    developer: "Ubisoft Montreal",
    review: 82,
    publisher: "Ubisoft",
    delivery: "Digital Key",
  },

  /* Far Cry 6 */
  {
    name: "Far Cry 6 (Ubisoft)",
    slug: toSlug("Far Cry 6 (Ubisoft)"),
    image: "/images/games/Far Cry 6.png",
    platform: "Ubisoft",
    platformImageIcon: "/images/icons/ubisoft-icon.png",
    edition: "Standard",
    description:
      "Far Cry 6 is an open-world shooter set in a revolution-torn Caribbean island ruled by a dictator. Fight to liberate your homeland.",
    price: 1290,
    countInStock: 132,
    numSales: 2344,
    releaseDate: "07-10-2021",
    developer: "Ubisoft Toronto",
    review: 78,
    publisher: "Ubisoft",
    delivery: "Digital Key",
  },

  /* Final Fantasy Origin Stranger Of Paradise */
  {
    name: "Final Fantasy Origin Stranger Of Paradise (PS)",
    slug: toSlug("Final Fantasy Origin Stranger Of Paradise (PS)"),
    image: "/images/games/Final Fantasy Origin Stranger Of Paradise.png",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Standard",
    description:
      "Stranger of Paradise: Final Fantasy Origin is a darker, action-focused take on the FF universe with intense, fast-paced combat.",
    price: 990,
    countInStock: 102,
    numSales: 1002,
    releaseDate: "18-03-2022",
    developer: "Team Ninja",
    review: 76,
    publisher: "Square Enix",
    delivery: "Physical DVD",
  },

  /* Final Fantasy VII Rebirth */
  {
    name: "Final Fantasy VII Rebirth (PS)",
    slug: toSlug("Final Fantasy VII Rebirth (PS)"),
    image: "/images/games/Final Fantasy VII Rebirth.jpg",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Deluxe",
    description:
      "Final Fantasy VII Rebirth continues Cloud’s journey in this reimagined epic with vast environments and intense narrative moments.",
    price: 2290,
    countInStock: 87,
    numSales: 2101,
    releaseDate: "29-02-2024",
    developer: "Square Enix",
    review: 91,
    publisher: "Square Enix",
    delivery: "Physical DVD",
  },

  /* Final Fantasy VII Remake */
  {
    name: "Final Fantasy VII Remake (Steam)",
    slug: toSlug("Final Fantasy VII Remake (Steam)"),
    image: "/images/games/Final Fantasy VII Remake.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Intergrade",
    description:
      "Final Fantasy VII Remake is a bold reimagining of the classic RPG, featuring modern graphics, action combat, and a rich story.",
    price: 1690,
    countInStock: 129,
    numSales: 2210,
    releaseDate: "17-06-2022",
    developer: "Square Enix",
    review: 89,
    publisher: "Square Enix",
    delivery: "Digital Key",
  },

  /* Final Fantasy X HD Remaster */
  {
    name: "Final Fantasy X HD Remaster (Steam)",
    slug: toSlug("Final Fantasy X HD Remaster (Steam)"),
    image: "/images/games/Final Fantasy X HD Remaster.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Standard",
    description:
      "Final Fantasy X/X-2 HD Remaster brings the beloved RPGs to modern platforms with enhanced visuals and audio.",
    price: 590,
    countInStock: 111,
    numSales: 3280,
    releaseDate: "13-05-2016",
    developer: "Virtuos",
    review: 88,
    publisher: "Square Enix",
    delivery: "Digital Key",
  },

  /* Final Fantasy XV */
  {
    name: "Final Fantasy XV (Steam)",
    slug: toSlug("Final Fantasy XV (Steam)"),
    image: "/images/games/Final Fantasy XV.jpg",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Royal",
    description:
      "Final Fantasy XV tells the story of Prince Noctis and his comrades in a modern fantasy world filled with epic action and bonds.",
    price: 890,
    countInStock: 126,
    numSales: 3110,
    releaseDate: "06-03-2018",
    developer: "Square Enix",
    review: 85,
    publisher: "Square Enix",
    delivery: "Digital Key",
  },
  {
    name: "Final Fantasy XV (PS)",
    slug: toSlug("Final Fantasy XV (PS)"),
    image: "/images/games/Final Fantasy XV.jpg",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.jpg",
    edition: "Royal",
    description:
      "Final Fantasy XV tells the story of Prince Noctis and his comrades in a modern fantasy world filled with epic action and bonds.",
    price: 990,
    countInStock: 93,
    numSales: 1901,
    releaseDate: "29-11-2016",
    developer: "Square Enix",
    review: 84,
    publisher: "Square Enix",
    delivery: "Physical DVD",
  },

  /* Final Fantasy XVI */
  {
    name: "Final Fantasy XVI (PS)",
    slug: toSlug("Final Fantasy XVI (PS)"),
    image: "/images/games/Final Fantasy XVI.png",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Standard",
    description:
      "Final Fantasy XVI introduces a darker tale of revenge and fate in a medieval fantasy world with powerful Eikons and cinematic combat.",
    price: 2390,
    countInStock: 72,
    numSales: 1789,
    releaseDate: "22-06-2023",
    developer: "Square Enix Creative Business Unit III",
    review: 88,
    publisher: "Square Enix",
    delivery: "Physical DVD",
  },
  /* Gears Of War 5 */
  {
    name: "Gears Of War 5 (Xbox)",
    slug: toSlug("Gears Of War 5 (Xbox)"),
    image: "/images/games/Gears Of War 5.png",
    platform: "Xbox",
    platformImageIcon: "/images/icons/xbox-icon.png",
    edition: "Standard",
    description:
      "Gears 5 is a third-person shooter developed by The Coalition and published by Xbox Game Studios. It continues the story of the Gears of War series with a focus on Kait Diaz.",
    price: 1490,
    countInStock: 215,
    numSales: 88,
    releaseDate: "10-09-2019",
    developer: "The Coalition",
    review: 84,
    publisher: "Xbox Game Studios",
    delivery: "Digital Key",
  },
  {
    name: "Gears Of War 5 (Steam)",
    slug: toSlug("Gears Of War 5 (Steam)"),
    image: "/images/games/Gears Of War 5.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Standard",
    description:
      "Gears 5 is a third-person shooter developed by The Coalition and published by Xbox Game Studios. It continues the story of the Gears of War series with a focus on Kait Diaz.",
    price: 1490,
    countInStock: 120,
    numSales: 77,
    releaseDate: "10-09-2019",
    developer: "The Coalition",
    review: 82,
    publisher: "Xbox Game Studios",
    delivery: "Digital Key",
  },

  /* Genshin Impact */
  {
    name: "Genshin Impact (PS)",
    slug: toSlug("Genshin Impact (PS)"),
    image: "/images/games/Genshin Impact.png",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Starter",
    description:
      "Genshin Impact is an open-world action RPG developed and published by miHoYo. It features an anime-style fantasy world with elemental combat and character switching.",
    price: 0,
    countInStock: 999,
    numSales: 1000,
    releaseDate: "28-09-2020",
    developer: "miHoYo",
    review: 85,
    publisher: "miHoYo",
    delivery: "Account",
  },

  /* Ghost Of Tsushima */
  {
    name: "Ghost Of Tsushima (PS)",
    slug: toSlug("Ghost Of Tsushima (PS)"),
    image: "/images/games/Ghost Of Tsushima.png",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Director's Cut",
    description:
      "Ghost of Tsushima is an action-adventure game developed by Sucker Punch Productions and published by Sony Interactive Entertainment. It follows a samurai during the Mongol invasion of Japan.",
    price: 1890,
    countInStock: 190,
    numSales: 93,
    releaseDate: "17-07-2020",
    developer: "Sucker Punch Productions",
    review: 91,
    publisher: "Sony Interactive Entertainment",
    delivery: "Physical DVD",
  },

  /* Ghost Recon Wildland */
  {
    name: "Ghost Recon Wildland (Ubisoft)",
    slug: toSlug("Ghost Recon Wildland (Ubisoft)"),
    image: "/images/games/Ghost Recon Wildland.png",
    platform: "Ubisoft",
    platformImageIcon: "/images/icons/ubisoft-icon.png",
    edition: "Gold",
    description:
      "Tom Clancy's Ghost Recon Wildlands is a tactical shooter developed by Ubisoft Paris. Players lead a special operations team fighting drug cartels in Bolivia.",
    price: 1290,
    countInStock: 165,
    numSales: 60,
    releaseDate: "07-03-2017",
    developer: "Ubisoft Paris",
    review: 78,
    publisher: "Ubisoft",
    delivery: "Digital Key",
  },

  /* God Of War Ragnarok */
  {
    name: "God Of War Ragnarok (PS)",
    slug: toSlug("God Of War Ragnarok (PS)"),
    image: "/images/games/God Of War Ragnarok.png",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Standard",
    description:
      "God of War Ragnarök is an action-adventure game developed by Santa Monica Studio and published by Sony Interactive Entertainment. It continues Kratos and Atreus’s journey through Norse mythology.",
    price: 2290,
    countInStock: 210,
    numSales: 95,
    releaseDate: "09-11-2022",
    developer: "Santa Monica Studio",
    review: 94,
    publisher: "Sony Interactive Entertainment",
    delivery: "Physical DVD",
  },

  /* God Of War */
  {
    name: "God Of War (Steam)",
    slug: toSlug("God Of War (Steam)"),
    image: "/images/games/God Of War.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Standard",
    description:
      "God of War is an action-adventure game developed by Santa Monica Studio and published by Sony Interactive Entertainment. It follows Kratos and Atreus on a journey through Norse realms.",
    price: 999,
    countInStock: 345,
    numSales: 110,
    releaseDate: "14-01-2022",
    developer: "Santa Monica Studio",
    review: 93,
    publisher: "Sony Interactive Entertainment",
    delivery: "Digital Key",
  },

  /* Godfall */
  {
    name: "Godfall (Epic Game)",
    slug: toSlug("Godfall (Epic Game)"),
    image: "/images/games/Godfall.png",
    platform: "Epic Game",
    platformImageIcon: "/images/icons/epic-icon.png",
    edition: "Deluxe",
    description:
      "Godfall is an action role-playing game developed by Counterplay Games and published by Gearbox Publishing. It features melee-focused combat in a high fantasy setting.",
    price: 790,
    countInStock: 80,
    numSales: 38,
    releaseDate: "12-11-2020",
    developer: "Counterplay Games",
    review: 72,
    publisher: "Gearbox Publishing",
    delivery: "Account",
  },

  /* Grandblue Fantasy Relink */
  {
    name: "Grandblue Fantasy Relink (Steam)",
    slug: toSlug("Grandblue Fantasy Relink (Steam)"),
    image: "/images/games/Grandblue Fantasy Relink.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Standard",
    description:
      "Granblue Fantasy: Relink is an action RPG developed by Cygames. It brings the popular mobile franchise into a full 3D console experience with real-time combat.",
    price: 1890,
    countInStock: 170,
    numSales: 42,
    releaseDate: "01-02-2024",
    developer: "Cygames",
    review: 88,
    publisher: "Cygames",
    delivery: "Digital Key",
  },
  {
    name: "Grandblue Fantasy Relink (PS)",
    slug: toSlug("Grandblue Fantasy Relink (PS)"),
    image: "/images/games/Grandblue Fantasy Relink.png",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Deluxe",
    description:
      "Granblue Fantasy: Relink is an action RPG developed by Cygames. It brings the popular mobile franchise into a full 3D console experience with real-time combat.",
    price: 1890,
    countInStock: 170,
    numSales: 42,
    releaseDate: "01-02-2024",
    developer: "Cygames",
    review: 88,
    publisher: "Cygames",
    delivery: "Digital Key",
  },

  /* GTA V */
  {
    name: "GTA V (Steam)",
    slug: toSlug("GTA V (Steam)"),
    image: "/images/games/GTA V.jpg",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Premium",
    description:
      "Grand Theft Auto V is an open-world action-adventure game developed by Rockstar North and published by Rockstar Games. It features a dynamic story across three protagonists in Los Santos.",
    price: 690,
    countInStock: 405,
    numSales: 600,
    releaseDate: "14-04-2015",
    developer: "Rockstar North",
    review: 94,
    publisher: "Rockstar Games",
    delivery: "Digital Key",
  },

  /* Guardians Of The Galaxy */
  {
    name: "Guardien Of The Galaxy (Epic Game)",
    slug: toSlug("Guardien Of The Galaxy (Epic Game)"),
    image: "/images/games/Guardien Of The Galaxy.png",
    platform: "Epic Game",
    platformImageIcon: "/images/icons/epic-icon.png",
    edition: "Standard",
    description:
      "Marvel’s Guardians of the Galaxy is an action-adventure game developed by Eidos-Montréal and published by Square Enix. Players take on the role of Star-Lord in a narrative-driven journey.",
    price: 890,
    countInStock: 132,
    numSales: 41,
    releaseDate: "26-10-2021",
    developer: "Eidos-Montréal",
    review: 81,
    publisher: "Square Enix",
    delivery: "Account",
  },

  /* Hellblade */
  {
    name: "Hellblade (Steam)",
    slug: toSlug("Hellblade (Steam)"),
    image: "/images/games/Hellblade.jpg",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Standard",
    description:
      "Hellblade: Senua's Sacrifice is an action-adventure game developed and published by Ninja Theory. It explores mental health through Norse mythology and Celtic culture.",
    price: 550,
    countInStock: 195,
    numSales: 72,
    releaseDate: "08-08-2017",
    developer: "Ninja Theory",
    review: 89,
    publisher: "Ninja Theory",
    delivery: "Digital Key",
  },

  /* Hitman 3 */
  {
    name: "Hitman 3 (Steam)",
    slug: toSlug("Hitman 3 (Steam)"),
    image: "/images/games/Hitman 3.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Deluxe",
    description:
      "Hitman 3 is a stealth action game developed and published by IO Interactive. It concludes the World of Assassination trilogy featuring Agent 47.",
    price: 1190,
    countInStock: 145,
    numSales: 56,
    releaseDate: "20-01-2021",
    developer: "IO Interactive",
    review: 86,
    publisher: "IO Interactive",
    delivery: "Digital Key",
  },

  /* Hogwarts Legacy */
  {
    name: "Hogwarts Legacy (Steam)",
    slug: toSlug("Hogwarts Legacy (Steam)"),
    image: "/images/games/Hogwarts Legacy.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Standard",
    description:
      "Hogwarts Legacy is an open-world action RPG developed by Avalanche Software and published by Warner Bros. Interactive Entertainment. Set in the Harry Potter universe during the 1800s.",
    price: 1990,
    countInStock: 220,
    numSales: 105,
    releaseDate: "10-02-2023",
    developer: "Avalanche Software",
    review: 87,
    publisher: "Warner Bros. Interactive Entertainment",
    delivery: "Digital Key",
  },

  /* Horizon Forbidden West */
  {
    name: "Horizon Forbidden West (PS)",
    slug: toSlug("Horizon Forbidden West (PS)"),
    image: "/images/games/Horizon Forbidden West.png",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Standard",
    description:
      "Horizon Forbidden West is an action role-playing game developed by Guerrilla Games and published by Sony Interactive Entertainment. It continues the story of Aloy as she ventures into the mysterious frontier known as the Forbidden West.",
    price: 2290,
    countInStock: 340,
    numSales: 58,
    releaseDate: "18-02-2022",
    developer: "Guerrilla Games",
    review: 88,
    publisher: "Sony Interactive Entertainment",
    delivery: "Physical DVD",
  },
  /* Horizon Zero Dawn */
  {
    name: "Horizon Zero Dawn (Steam)",
    slug: toSlug("Horizon Zero Dawn (Steam)"),
    image: "/images/games/Horizon Zero Dawn.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Complete",
    description:
      "Horizon Zero Dawn is an action role-playing game developed by Guerrilla Games and published by Sony Interactive Entertainment. It follows Aloy, a hunter in a world overrun by machines.",
    price: 749,
    countInStock: 430,
    numSales: 87,
    releaseDate: "07-08-2020",
    developer: "Guerrilla Games",
    review: 89,
    publisher: "Sony Interactive Entertainment",
    delivery: "Digital Key",
  },
  /* Just Cause 4 */
  {
    name: "Just Cause 4 (Steam)",
    slug: toSlug("Just Cause 4 (Steam)"),
    image: "/images/games/Just Cause 4.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Gold",
    description:
      "Just Cause 4 is an action-adventure game developed by Avalanche Studios and published by Square Enix. It features explosive gameplay and an open world set in the fictional South American country of Solís.",
    price: 599,
    countInStock: 220,
    numSales: 44,
    releaseDate: "04-12-2018",
    developer: "Avalanche Studios",
    review: 75,
    publisher: "Square Enix",
    delivery: "Digital Key",
  },
  /* Lies of P */
  {
    name: "Lies of P (Steam)",
    slug: toSlug("Lies of P (Steam)"),
    image: "/images/games/Lies of P.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Deluxe",
    description:
      "Lies of P is a soulslike action RPG developed by Neowiz Games and Round8 Studio. Inspired by the story of Pinocchio, players navigate a dark Belle Époque world filled with mystery and horror.",
    price: 1390,
    countInStock: 310,
    numSales: 53,
    releaseDate: "19-09-2023",
    developer: "Round8 Studio",
    review: 82,
    publisher: "Neowiz Games",
    delivery: "Digital Key",
  },
  /* Like A Dragon Gaiden */
  {
    name: "Like A Dragon Gaiden (Steam)",
    slug: toSlug("Like A Dragon Gaiden (Steam)"),
    image: "/images/games/Like A Dragon Gaiden.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Standard",
    description:
      "Like a Dragon Gaiden: The Man Who Erased His Name is an action-adventure game developed by Ryu Ga Gotoku Studio and published by Sega. It follows Kazuma Kiryu in a side story that bridges Yakuza 6 and Yakuza: Like a Dragon.",
    price: 1199,
    countInStock: 250,
    numSales: 39,
    releaseDate: "09-11-2023",
    developer: "Ryu Ga Gotoku Studio",
    review: 86,
    publisher: "Sega",
    delivery: "Digital Key",
  },
  /* Metal Gears Rising Revengence */
  {
    name: "Metal Gears Rising Revengence (Steam)",
    slug: toSlug("Metal Gears Rising Revengence (Steam)"),
    image: "/images/games/Metal Gears Rising Revengence.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Standard",
    description:
      "Metal Gear Rising: Revengeance is a hack and slash action game developed by PlatinumGames and published by Konami. It follows Raiden, a cyborg ninja, in a fast-paced, action-packed adventure.",
    price: 399,
    countInStock: 300,
    numSales: 71,
    releaseDate: "09-01-2014",
    developer: "PlatinumGames",
    review: 83,
    publisher: "Konami",
    delivery: "Digital Key",
  },
  {
    name: "Metal Gears Rising Revengence (Xbox)",
    slug: toSlug("Metal Gears Rising Revengence (Xbox)"),
    image: "/images/games/Metal Gears Rising Revengence.png",
    platform: "Xbox",
    platformImageIcon: "/images/icons/xbox-icon.png",
    edition: "Standard",
    description:
      "Metal Gear Rising: Revengeance is a hack and slash action game developed by PlatinumGames and published by Konami. It follows Raiden, a cyborg ninja, in a fast-paced, action-packed adventure.",
    price: 399,
    countInStock: 300,
    numSales: 71,
    releaseDate: "09-01-2014",
    developer: "PlatinumGames",
    review: 83,
    publisher: "Konami",
    delivery: "Digital Key",
  },
  /* Minecraft */
  {
    name: "Minecraft (Microsoft)",
    slug: toSlug("Minecraft (Microsoft)"),
    image: "/images/games/Minecraft.jpg",
    platform: "Microsoft",
    platformImageIcon: "/images/icons/microsoft-icon.png",
    edition: "Standard",
    description:
      "Minecraft is a sandbox video game developed by Mojang Studios. It allows players to explore, build, and survive in a blocky, procedurally generated 3D world.",
    price: 899,
    countInStock: 500,
    numSales: 112,
    releaseDate: "18-11-2011",
    developer: "Mojang Studios",
    review: 95,
    publisher: "Mojang Studios",
    delivery: "Account",
  },
  /* Mirror Edge Catalyst */
  {
    name: "Mirror Edge Catalyst (Steam)",
    slug: toSlug("Mirror Edge Catalyst (Steam)"),
    image: "/images/games/Mirror Edge Catalyst.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Standard",
    description:
      "Mirror's Edge Catalyst is a first-person action-adventure platformer developed by DICE and published by Electronic Arts. It serves as a reboot of the original Mirror's Edge.",
    price: 690,
    countInStock: 210,
    numSales: 28,
    releaseDate: "07-06-2016",
    developer: "DICE",
    review: 78,
    publisher: "Electronic Arts",
    delivery: "Digital Key",
  },
  {
    name: "Mirror Edge Catalyst (EA)",
    slug: toSlug("Mirror Edge Catalyst (EA)"),
    image: "/images/games/Mirror Edge Catalyst.png",
    platform: "EA",
    platformImageIcon: "/images/icons/ea-icon.png",
    edition: "Standard",
    description:
      "Mirror's Edge Catalyst is a first-person action-adventure platformer developed by DICE and published by Electronic Arts. It serves as a reboot of the original Mirror's Edge.",
    price: 690,
    countInStock: 190,
    numSales: 22,
    releaseDate: "07-06-2016",
    developer: "DICE",
    review: 78,
    publisher: "Electronic Arts",
    delivery: "Digital Key",
  },
  /* Mirror Edge  */
  {
    name: "Mirror Edge (EA)",
    slug: toSlug("Mirror Edge (EA)"),
    image: "/images/games/Mirror Edge.jpg",
    platform: "EA",
    platformImageIcon: "/images/icons/ea-icon.png",
    edition: "Standard",
    description:
      "Mirror's Edge Catalyst is a first-person action-adventure platformer developed by DICE and published by Electronic Arts. It serves as a reboot of the original Mirror's Edge.",
    price: 690,
    countInStock: 190,
    numSales: 22,
    releaseDate: "07-06-2016",
    developer: "DICE",
    review: 78,
    publisher: "Electronic Arts",
    delivery: "Digital Key",
  },
  /* Monster Hunter Rise Sunbreak */
  {
    name: "Monster Hunter Rise Sunbreak (Steam)",
    slug: toSlug("Monster Hunter Rise Sunbreak (Steam)"),
    image: "/images/games/Monster Hunter Rise Sunbreak.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Standard",
    description:
      "Monster Hunter Rise: Sunbreak is a major expansion to Monster Hunter Rise, developed and published by Capcom. It adds new monsters, mechanics, and story elements.",
    price: 1190,
    countInStock: 320,
    numSales: 68,
    releaseDate: "30-06-2022",
    developer: "Capcom",
    review: 87,
    publisher: "Capcom",
    delivery: "Digital Key",
  },
  {
    name: "Monster Hunter Rise Sunbreak (Nintendo)",
    slug: toSlug("Monster Hunter Rise Sunbreak (Nintendo)"),
    image: "/images/games/Monster Hunter Rise Sunbreak.png",
    platform: "Nintendo",
    platformImageIcon: "/images/icons/nintendo-icon.png",
    edition: "Deluxe",
    description:
      "Monster Hunter Rise: Sunbreak is a major expansion to Monster Hunter Rise, developed and published by Capcom. It adds new monsters, mechanics, and story elements.",
    price: 1590,
    countInStock: 320,
    numSales: 68,
    releaseDate: "30-06-2022",
    developer: "Capcom",
    review: 87,
    publisher: "Capcom",
    delivery: "Digital Key",
  },
  /* Monster Hunter Wilds */
  {
    name: "Monster Hunter Wilds (PS)",
    slug: toSlug("Monster Hunter Wilds (PS)"),
    image: "/images/games/Monster Hunter Wilds.png",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Standard",
    description:
      "Monster Hunter Wilds is an upcoming action role-playing game developed and published by Capcom. It continues the series' tradition of epic monster battles and cooperative gameplay.",
    price: 2199,
    countInStock: 305,
    numSales: 12,
    releaseDate: "28-02-2025",
    developer: "Capcom",
    review: 89,
    publisher: "Capcom",
    delivery: "Physical DVD",
  },

  /* Monster Hunter World Iceborne */
  {
    name: "Monster Hunter World Iceborne (Steam)",
    slug: toSlug("Monster Hunter World Iceborne (Steam)"),
    image: "/images/games/Monster Hunter World Iceborne.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Master",
    description:
      "Monster Hunter World: Iceborne is a massive expansion for Monster Hunter: World, adding new monsters, areas, and mechanics to deepen the hunting experience.",
    price: 849,
    countInStock: 198,
    numSales: 97,
    releaseDate: "06-09-2019",
    developer: "Capcom",
    review: 90,
    publisher: "Capcom",
    delivery: "Digital Key",
  },
  {
    name: "Monster Hunter World Iceborne (PS)",
    slug: toSlug("Monster Hunter World Iceborne (PS)"),
    image: "/images/games/Monster Hunter World Iceborne.png",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Master",
    description:
      "Monster Hunter World: Iceborne is a massive expansion for Monster Hunter: World, adding new monsters, areas, and mechanics to deepen the hunting experience.",
    price: 1199,
    countInStock: 133,
    numSales: 76,
    releaseDate: "06-09-2019",
    developer: "Capcom",
    review: 88,
    publisher: "Capcom",
    delivery: "Physical DVD",
  },

  /* NFS Heat */
  {
    name: "NFS Heat (EA)",
    slug: toSlug("NFS Heat (EA)"),
    image: "/images/games/NFS Heat.png",
    platform: "EA",
    platformImageIcon: "/images/icons/ea-icon.png",
    edition: "Standard",
    description:
      "Need for Speed Heat is a racing game developed by Ghost Games and published by Electronic Arts. It blends street racing culture with dynamic gameplay and intense cop chases.",
    price: 699,
    countInStock: 213,
    numSales: 55,
    releaseDate: "08-11-2019",
    developer: "Ghost Games",
    review: 82,
    publisher: "Electronic Arts",
    delivery: "Digital Key",
  },

  /* Nier R Automata */
  {
    name: "Nier R Automata (Steam)",
    slug: toSlug("Nier R Automata (Steam)"),
    image: "/images/games/Nier R Automata.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Game of the YoRHa",
    description:
      "NieR: Automata is an action RPG developed by PlatinumGames and published by Square Enix. It features a profound story, stunning combat, and philosophical undertones.",
    price: 999,
    countInStock: 287,
    numSales: 118,
    releaseDate: "17-03-2017",
    developer: "PlatinumGames",
    review: 91,
    publisher: "Square Enix",
    delivery: "Digital Key",
  },
  {
    name: "Nier R Automata (PS)",
    slug: toSlug("Nier R Automata (PS)"),
    image: "/images/games/Nier R Automata.png",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Game of the YoRHa",
    description:
      "NieR: Automata is an action RPG developed by PlatinumGames and published by Square Enix. It features a profound story, stunning combat, and philosophical undertones.",
    price: 1199,
    countInStock: 190,
    numSales: 91,
    releaseDate: "23-02-2017",
    developer: "PlatinumGames",
    review: 88,
    publisher: "Square Enix",
    delivery: "Physical DVD",
  },

  /* Rachet & Clank Rift Apart */
  {
    name: "Rachet & Clank Rift Apart (PS)",
    slug: toSlug("Rachet & Clank Rift Apart (PS)"),
    image: "/images/games/Rachet & Clank Rift Apart.png",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Standard",
    description:
      "Ratchet & Clank: Rift Apart is a visually stunning action-adventure platformer developed by Insomniac Games and published by Sony Interactive Entertainment.",
    price: 2099,
    countInStock: 122,
    numSales: 62,
    releaseDate: "11-06-2021",
    developer: "Insomniac Games",
    review: 87,
    publisher: "Sony Interactive Entertainment",
    delivery: "Physical DVD",
  },

  /* Red Dead Redemtion 2 */
  {
    name: "Red Dead Redemtion 2 (Steam)",
    slug: toSlug("Red Dead Redemtion 2 (Steam)"),
    image: "/images/games/Red Dead Redemtion 2.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Ultimate",
    description:
      "Red Dead Redemption 2 is an epic tale of life in America at the dawn of the modern age. Developed by Rockstar Games, it's a masterpiece of storytelling and open-world design.",
    price: 1399,
    countInStock: 289,
    numSales: 152,
    releaseDate: "26-10-2018",
    developer: "Rockstar Games",
    review: 96,
    publisher: "Rockstar Games",
    delivery: "Digital Key",
  },
  {
    name: "Red Dead Redemtion 2 (PS)",
    slug: toSlug("Red Dead Redemtion 2 (PS)"),
    image: "/images/games/Red Dead Redemtion 2.png",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Ultimate",
    description:
      "Red Dead Redemption 2 is an epic tale of life in America at the dawn of the modern age. Developed by Rockstar Games, it's a masterpiece of storytelling and open-world design.",
    price: 1599,
    countInStock: 202,
    numSales: 143,
    releaseDate: "26-10-2018",
    developer: "Rockstar Games",
    review: 94,
    publisher: "Rockstar Games",
    delivery: "Physical DVD",
  },

  /* Remnent 2 */
  {
    name: "Remnent 2 (Steam)",
    slug: toSlug("Remnent 2 (Steam)"),
    image: "/images/games/Remnent 2.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Standard",
    description:
      "Remnant II is a third-person action-survival shooter developed by Gunfire Games. Players must face deadly creatures and god-like bosses across terrifying worlds.",
    price: 1099,
    countInStock: 99,
    numSales: 65,
    releaseDate: "25-07-2023",
    developer: "Gunfire Games",
    review: 84,
    publisher: "Gearbox Publishing",
    delivery: "Digital Key",
  },
  /* Resident Evil 4 */
  {
    name: "Resident Evil 4 (Steam)",
    slug: toSlug("Resident Evil 4 (Steam)"),
    image: "/images/games/Resident Evil 4.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Deluxe",
    description:
      "Resident Evil 4 is a survival horror remake of the 2005 classic, revitalized with modern graphics, controls, and terrifying atmosphere by Capcom.",
    price: 1490,
    countInStock: 210,
    numSales: 130,
    releaseDate: "24-03-2023",
    developer: "Capcom",
    review: 93,
    publisher: "Capcom",
    delivery: "Digital Key",
  },
  {
    name: "Resident Evil 4 (PS)",
    slug: toSlug("Resident Evil 4 (PS)"),
    image: "/images/games/Resident Evil 4.png",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Deluxe",
    description:
      "Resident Evil 4 is a survival horror remake of the 2005 classic, revitalized with modern graphics, controls, and terrifying atmosphere by Capcom.",
    price: 1790,
    countInStock: 160,
    numSales: 102,
    releaseDate: "24-03-2023",
    developer: "Capcom",
    review: 90,
    publisher: "Capcom",
    delivery: "Physical DVD",
  },

  /* Rise Of Tomb Raider */
  {
    name: "Rise Of Tomb Raider (Steam)",
    slug: toSlug("Rise Of Tomb Raider (Steam)"),
    image: "/images/games/Rise Of Tomb Raider.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "20 Year Celebration",
    description:
      "Rise of the Tomb Raider follows Lara Croft as she ventures into Siberia in search of the legendary city of Kitezh, facing deadly challenges and ancient secrets.",
    price: 690,
    countInStock: 188,
    numSales: 75,
    releaseDate: "10-11-2015",
    developer: "Crystal Dynamics",
    review: 86,
    publisher: "Square Enix",
    delivery: "Digital Key",
  },

  /* Scarlet Nexus */
  {
    name: "Scarlet Nexus (PS)",
    slug: toSlug("Scarlet Nexus (PS)"),
    image: "/images/games/Scarlet Nexus.jpg",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Deluxe",
    description:
      "Scarlet Nexus is a brain-punk action RPG where players wield powerful psychic abilities in a futuristic world threatened by mysterious mutants.",
    price: 1290,
    countInStock: 142,
    numSales: 58,
    releaseDate: "25-06-2021",
    developer: "Bandai Namco",
    review: 82,
    publisher: "Bandai Namco",
    delivery: "Physical DVD",
  },
  /* Sea Of Stars */
  {
    name: "Sea Of Stars (Steam)",
    slug: toSlug("Sea Of Stars (Steam)"),
    image: "/images/games/Sea Of Stars.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Standard",
    description:
      "Sea of Stars is a turn-based RPG inspired by the classics, telling the story of two Children of the Solstice who combine the powers of the sun and moon to perform Eclipse Magic.",
    price: 690,
    countInStock: 180,
    numSales: 45,
    releaseDate: "29-08-2023",
    developer: "Sabotage Studio",
    review: 89,
    publisher: "Sabotage Studio",
    delivery: "Digital Key",
  },

  /* Sekiro Shadow Die Twice */
  {
    name: "Sekiro Shadow Die Twice (Steam)",
    slug: toSlug("Sekiro Shadow Die Twice (Steam)"),
    image: "/images/games/Sekiro Shadow Die Twice.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Game of the Year",
    description:
      "Sekiro: Shadows Die Twice is an action-adventure game that places you in the shoes of a shinobi on a mission to rescue his kidnapped lord in Sengoku-era Japan.",
    price: 1390,
    countInStock: 205,
    numSales: 111,
    releaseDate: "22-03-2019",
    developer: "FromSoftware",
    review: 91,
    publisher: "Activision",
    delivery: "Digital Key",
  },
  {
    name: "Sekiro Shadow Die Twice (PS)",
    slug: toSlug("Sekiro Shadow Die Twice (PS)"),
    image: "/images/games/Sekiro Shadow Die Twice.png",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Game of the Year",
    description:
      "Sekiro: Shadows Die Twice is an action-adventure game that places you in the shoes of a shinobi on a mission to rescue his kidnapped lord in Sengoku-era Japan.",
    price: 1490,
    countInStock: 135,
    numSales: 89,
    releaseDate: "22-03-2019",
    developer: "FromSoftware",
    review: 92,
    publisher: "Activision",
    delivery: "Physical DVD",
  },

  /* Shadow Of Tomb Raider */
  {
    name: "Shadow Of Tomb Raider (Steam)",
    slug: toSlug("Shadow Of Tomb Raider (Steam)"),
    image: "/images/games/Shadow Of Tomb Raider.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Definitive",
    description:
      "Shadow of the Tomb Raider concludes Lara Croft’s origin story as she becomes the Tomb Raider, exploring deadly jungles and ancient tombs to stop a Maya apocalypse.",
    price: 790,
    countInStock: 190,
    numSales: 64,
    releaseDate: "14-09-2018",
    developer: "Eidos-Montréal",
    review: 84,
    publisher: "Square Enix",
    delivery: "Digital Key",
  },

  /* Spider Man Mile Morales */
  {
    name: "Spider Man Mile Morales (PS)",
    slug: toSlug("Spider Man Mile Morales (PS)"),
    image: "/images/games/Spider Man Mile Morales.png",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Launch",
    description:
      "Marvel’s Spider-Man: Miles Morales is a superhero game following the journey of young Miles as he masters new powers to become his own Spider-Man.",
    price: 1790,
    countInStock: 165,
    numSales: 77,
    releaseDate: "12-11-2020",
    developer: "Insomniac Games",
    review: 88,
    publisher: "Sony Interactive Entertainment",
    delivery: "Physical DVD",
  },

  /* Spider Man */
  {
    name: "Spider Man (Steam)",
    slug: toSlug("Spider Man (Steam)"),
    image: "/images/games/Spider Man.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Remastered",
    description:
      "Marvel’s Spider-Man Remastered is a high-octane open-world action game featuring Peter Parker as he balances crime-fighting and personal struggles in New York City.",
    price: 1590,
    countInStock: 140,
    numSales: 83,
    releaseDate: "12-08-2022",
    developer: "Insomniac Games",
    review: 89,
    publisher: "Sony Interactive Entertainment",
    delivery: "Digital Key",
  },

  /* Star Rail */
  {
    name: "Star Rail (Epic Game)",
    slug: toSlug("Star Rail (Epic Game)"),
    image: "/images/games/Star Rail.png",
    platform: "Epic Game",
    platformImageIcon: "/images/icons/epic-icon.png",
    edition: "Standard",
    description:
      "Honkai: Star Rail is a turn-based space fantasy RPG where players journey across planets aboard the Astral Express, battling using strategic combat systems.",
    price: 0,
    countInStock: 999,
    numSales: 999,
    releaseDate: "26-04-2023",
    developer: "HoYoverse",
    review: 85,
    publisher: "HoYoverse",
    delivery: "Account",
  },

  /* Star Wars Jedi Fallen Order */
  {
    name: "Star Wars Jedi Fallen Order (Steam)",
    slug: toSlug("Star Wars Jedi Fallen Order (Steam)"),
    image: "/images/games/Star Wars Jedi Fallen Order.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Deluxe",
    description:
      "Star Wars Jedi: Fallen Order is a third-person action-adventure game that follows Cal Kestis, a young Jedi Padawan on the run from the Empire.",
    price: 990,
    countInStock: 148,
    numSales: 101,
    releaseDate: "15-11-2019",
    developer: "Respawn Entertainment",
    review: 87,
    publisher: "EA",
    delivery: "Digital Key",
  },

  /* Star Wars Jedi Survivor */
  {
    name: "Star Wars Jedi Survivor (Steam)",
    slug: toSlug("Star Wars Jedi Survivor (Steam)"),
    image: "/images/games/Star Wars Jedi Survivor.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Standard",
    description:
      "Star Wars Jedi: Survivor continues the story of Cal Kestis in a galaxy-spanning journey filled with new Force powers, allies, and epic lightsaber battles.",
    price: 1990,
    countInStock: 122,
    numSales: 65,
    releaseDate: "28-04-2023",
    developer: "Respawn Entertainment",
    review: 81,
    publisher: "EA",
    delivery: "Digital Key",
  },

  /* Tales Of Arise */
  {
    name: "Tales Of Arise (PS)",
    slug: toSlug("Tales Of Arise (PS)"),
    image: "/images/games/Tales Of Arise.png",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Standard",
    description:
      "Tales of Arise is a JRPG that follows two heroes from different worlds united to fight oppression in a beautiful, story-rich adventure with action-packed combat.",
    price: 1690,
    countInStock: 152,
    numSales: 74,
    releaseDate: "10-09-2021",
    developer: "Bandai Namco",
    review: 86,
    publisher: "Bandai Namco",
    delivery: "Physical DVD",
  },

  /* The Last Of Us Part II Remastered */
  {
    name: "The Last Of Us Part II Remastered (PS)",
    slug: toSlug("The Last Of Us Part II Remastered (PS)"),
    image: "/images/games/The Last Of Us Part II Remastered.png",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Remastered",
    description:
      "The Last of Us Part II Remastered offers an upgraded version of the acclaimed sequel, exploring Ellie’s harrowing journey with enhanced visuals and gameplay.",
    price: 1790,
    countInStock: 133,
    numSales: 91,
    releaseDate: "19-01-2024",
    developer: "Naughty Dog",
    review: 92,
    publisher: "Sony Interactive Entertainment",
    delivery: "Physical DVD",
  },
  /* The Last Of Us Remake */
  {
    name: "The Last Of Us Remake (PS)",
    slug: toSlug("The Last Of Us Remake (PS)"),
    image: "/images/games/The Last Of Us Remake.png",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Remake",
    description:
      "The Last of Us Remake rebuilds the beloved original with modernized gameplay, improved controls, and enhanced visuals while retaining the emotional narrative.",
    price: 1890,
    countInStock: 145,
    numSales: 88,
    releaseDate: "02-09-2022",
    developer: "Naughty Dog",
    review: 94,
    publisher: "Sony Interactive Entertainment",
    delivery: "Physical DVD",
  },

  /* The Legend Of Zelda Breath Of The Wild */
  {
    name: "The Legend Of Zelda Breath Of The Wild (Nintendo)",
    slug: toSlug("The Legend Of Zelda Breath Of The Wild (Nintendo)"),
    image: "/images/games/The Legend Of Zelda Breath Of The Wild.png",
    platform: "Nintendo",
    platformImageIcon: "/images/icons/nintendo-icon.png",
    edition: "Standard",
    description:
      "The Legend of Zelda: Breath of the Wild is an open-world adventure that redefines exploration and discovery in the beloved Zelda universe.",
    price: 1790,
    countInStock: 110,
    numSales: 73,
    releaseDate: "03-03-2017",
    developer: "Nintendo",
    review: 97,
    publisher: "Nintendo",
    delivery: "Physical Cartridge",
  },

  /* The Witcher 3 */
  {
    name: "The Witcher 3 (Steam)",
    slug: toSlug("The Witcher 3 (Steam)"),
    image: "/images/games/The Witcher 3.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Game of the Year",
    description:
      "The Witcher 3: Wild Hunt is a massive open-world RPG where players become Geralt of Rivia, a monster hunter caught in a war-torn world.",
    price: 690,
    countInStock: 190,
    numSales: 126,
    releaseDate: "18-05-2015",
    developer: "CD Projekt Red",
    review: 96,
    publisher: "CD Projekt",
    delivery: "Digital Key",
  },
  {
    name: "The Witcher 3 (PS)",
    slug: toSlug("The Witcher 3 (PS)"),
    image: "/images/games/The Witcher 3.png",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Game of the Year",
    description:
      "The Witcher 3: Wild Hunt is a massive open-world RPG where players become Geralt of Rivia, a monster hunter caught in a war-torn world.",
    price: 890,
    countInStock: 120,
    numSales: 85,
    releaseDate: "18-05-2015",
    developer: "CD Projekt Red",
    review: 95,
    publisher: "CD Projekt",
    delivery: "Physical DVD",
  },

  /* Tiny Tina Wonderlands */
  {
    name: "Tiny Tina Wonderlands (Epic Game)",
    slug: toSlug("Tiny Tina Wonderlands (Epic Game)"),
    image: "/images/games/Tiny Tina Wonderlands.png",
    platform: "Epic Game",
    platformImageIcon: "/images/icons/epic-icon.png",
    edition: "Chaotic Great",
    description:
      "Tiny Tina’s Wonderlands is a fantasy-themed looter-shooter adventure set in a chaotic world filled with magic, monsters, and mayhem.",
    price: 1290,
    countInStock: 95,
    numSales: 51,
    releaseDate: "25-03-2022",
    developer: "Gearbox Software",
    review: 82,
    publisher: "2K",
    delivery: "Digital Key",
  },

  /* Uncharted 4 */
  {
    name: "Uncharted 4 (PS)",
    slug: toSlug("Uncharted 4 (PS)"),
    image: "/images/games/Uncharted 4.png",
    platform: "PS",
    platformImageIcon: "/images/icons/ps-icon.png",
    edition: "Standard",
    description:
      "Uncharted 4: A Thief’s End follows Nathan Drake on one last globe-trotting treasure hunt, filled with action-packed set pieces and heartfelt storytelling.",
    price: 790,
    countInStock: 130,
    numSales: 92,
    releaseDate: "10-05-2016",
    developer: "Naughty Dog",
    review: 93,
    publisher: "Sony Interactive Entertainment",
    delivery: "Physical DVD",
  },

  /* Watch Dog Legion */
  {
    name: "Watch Dog Legion (Steam)",
    slug: toSlug("Watch Dog Legion (Steam)"),
    image: "/images/games/Watch Dog Legion.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Gold",
    description:
      "Watch Dogs: Legion lets players recruit anyone in a near-future London to join the resistance and fight back against surveillance and authoritarianism.",
    price: 690,
    countInStock: 100,
    numSales: 66,
    releaseDate: "29-10-2020",
    developer: "Ubisoft",
    review: 75,
    publisher: "Ubisoft",
    delivery: "Digital Key",
  },

  /* Wolong Dynasty */
  {
    name: "Wolong Dynasty (Steam)",
    slug: toSlug("Wolong Dynasty (Steam)"),
    image: "/images/games/Wolong Dynasty.png",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Standard",
    description:
      "Wo Long: Fallen Dynasty is a dark fantasy action RPG set in the chaotic Three Kingdoms period, blending Chinese mythology with intense combat.",
    price: 1490,
    countInStock: 97,
    numSales: 41,
    releaseDate: "03-03-2023",
    developer: "Team Ninja",
    review: 79,
    publisher: "Koei Tecmo",
    delivery: "Digital Key",
  },
  {
    name: "Wolong Dynasty (Xbox)",
    slug: toSlug("Wolong Dynasty (Xbox)"),
    image: "/images/games/Wolong Dynasty.png",
    platform: "Xbox",
    platformImageIcon: "/images/icons/xbox-icon.png",
    edition: "Standard",
    description:
      "Wo Long: Fallen Dynasty is a dark fantasy action RPG set in the chaotic Three Kingdoms period, blending Chinese mythology with intense combat.",
    price: 1590,
    countInStock: 80,
    numSales: 30,
    releaseDate: "03-03-2023",
    developer: "Team Ninja",
    review: 80,
    publisher: "Koei Tecmo",
    delivery: "Digital Key",
  },

  /* Yakuza Like A Dragon */
  {
    name: "Yakuza Like A Dragon (Steam)",
    slug: toSlug("Yakuza Like A Dragon (Steam)"),
    image: "/images/games/Yakuza Like A Dragon.jpg",
    platform: "Steam",
    platformImageIcon: "/images/icons/steam-icon.png",
    edition: "Day One",
    description:
      "Yakuza: Like a Dragon is a turn-based RPG that introduces new protagonist Ichiban Kasuga as he navigates the criminal underworld of Yokohama.",
    price: 890,
    countInStock: 108,
    numSales: 77,
    releaseDate: "10-11-2020",
    developer: "Ryu Ga Gotoku Studio",
    review: 87,
    publisher: "SEGA",
    delivery: "Digital Key",
  },
];

const data = {
  products,
  headerMenus: [
    { name: "PC", href: "/pc" },
    { name: "PS", href: "/ps" },
    { name: "XBOX", href: "/xbox" },
    { name: "NINTENDO", href: "/nintendo" },
    { name: "EPIC GAME", href: "/epic-game" },
    { name: "Ubisoft", href: "/ubisoft" },
    { name: "DAILY DEALS", href: "/daily-deals" },
    { name: "NEWS", href: "/news" },
    { name: "COMING SOON", href: "/coming-soon" },
  ],
  homeCarousels: [
    {
      name: "Monster Hunter Wilds (PS)",
      image: "/images/home-carousel/Monster Hunter Wilds.jpg",
      href: "/monster-hunter-wilds-ps",
      buttonCaption: "Buy Now",
    },
    {
      name: "The Legend Of Zelda Breath Of The Wild (Nintendo)",
      image: "/images/home-carousel/The Legend Of Zelda Breath Of The Wild.jpg",
      href: "/the-legend-of-zelda-breath-of-the-wild-nintendo",
      buttonCaption: "See This",
    },
    {
      name: "The Last Of Us Part II Remastered (PS) ",
      image: "/images/home-carousel/The Last Of Us Part II Remastered.jpg",
      href: "/the-last-of-us-part-ii-remaster-ps",
      buttonCaption: "Release Now",
    },
    {
      name: "God Of War Ragnarok (PS)",
      image: "/images/home-carousel/God Of War Ragnarok.jpeg",
      href: "/god-of-war-ragnarok-ps",
      buttonCaption: "Shop Now",
    },
  ],
};
export default data;
